-- AlterTable
ALTER TABLE "produtos" ADD COLUMN     "alturaCm" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN     "comprimentoCm" INTEGER NOT NULL DEFAULT 28,
ADD COLUMN     "larguraCm" INTEGER NOT NULL DEFAULT 22,
ADD COLUMN     "pesoEmGramas" INTEGER NOT NULL DEFAULT 300;
